### ISSUE TITLE
Receive response instantly from authentication session status request

### ISSUE THREAD

**Issue by JorgenHeinsoo** [SK-EID/MID#10]
From API documentation on 'timeoutMs':
> For very low values the service silently reverts to configuration specific minimum value (can change, value around 1000ms)

So each authentication session status check request waits minimum 1 second before returning a response.

Currently implementing Mobile-ID authentication in a service where it is not practical to keep threads open by long-polling styled solution.
We are querying authentication session status multiple times (with delayed ~5 second timeout in between) in a synchronous manner and expect response to be returned immediately.
That minimum 1 second adds up in keeping the threads busy and might become a burden as load increases.

Could that limit be removed or lowered?
Is the only reason of that minimum to prevent incorrectly implementing clients from spamming the service?

**Comment by jalukse** [comment]
> Could that limit be removed or lowered?

No
> Is the only reason of that minimum to prevent incorrectly implementing clients from spamming the service?

Yes
