### ISSUE TITLE
Error codes on test number wiki page don't match API documentation

### ISSUE THREAD

**Issue by moll** [SK-EID/MID#13]
Hey,

https://github.com/SK-EID/MID/wiki/Test-number-for-automated-testing-in-DEMO lists `EXPIRED_TRANSACTION` as one of the possible error codes, but the current live demo server and https://github.com/SK-EID/MID#338-session-end-result-codes list it as `TIMEOUT`. Might want to fix the wiki there.

Cheers

**Comment by erkoumal** [comment]
Hello,

Thank you for pointing it out! Wiki has been fixed.
