### ISSUE TITLE
MID Authentication - Personal Data

### ISSUE THREAD

**Issue by weilah** [SK-EID/MID#7]
Is (or will be) there a way for the Relying Party to retrieve the End User personal details using the new REST API such as Name, Surname, Date of birth, gender... and so on?

**Comment by aasaru** [comment]
The signing and authentication certificate holds End User name, country and national identiy number (you can parse gender and date of birth from that). 
You can either fetch signing certificate with separate request or in case of authentication - authentication certificate is returned as a response for successful authentication

https://github.com/SK-EID/mid-rest-java-client
https://github.com/SK-EID/mid-rest-php-client
have example code how the authentication certificate is parsed.

And if you use 
https://github.com/SK-EID/mid-rest-java-demo or
https://github.com/SK-EID/mid-rest-php-demo
to do a authentication then in the end the End User certificate is parsed and the details are printed to the screen.

I hope that helps.

**Comment by weilah** [comment]
It helps! Thanks for getting back to me @aasaru I was already doing the "parse identity number" approach, so I guess I'm fine.

Thanks for the good work and the beautiful documentation
